backend:
  name: github
  repo: pm6482545-lang/Bethania-Academy # This matches your GitHub repository
  branch: main # This is your active branch
  site_domain: pm6482545-lang.github.io/Bethania-Academy/

media_folder: "images/uploads" # Where school photos will be stored
public_folder: "/images/uploads"

collections:
  - name: "announcements"
    label: "School Announcements"
    folder: "announcements" # The folder where news files will go
    create: true # Allows the school to create NEW posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Headline", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Message Content", name: "body", widget: "markdown"}
